import { Controller, Get, Logger } from '@nestjs/common'
import { ApiTags, ApiOperation, ApiResponse } from '@nestjs/swagger'
import { ChampionsService } from './champions.service'
import type { AllSkinsSplashArts } from '@loltimeflash/shared'

@ApiTags('champions')
@Controller('champions')
export class ChampionsController {
  private readonly logger = new Logger(ChampionsController.name)

  constructor(private readonly championsService: ChampionsService) {}

  /**
   * GET /champions/skins
   * Fetch all champions with their splash arts from Data Dragon API
   * Cached for 24 hours
   */
  @Get('skins')
  @ApiOperation({ 
    summary: 'Get all champion skins', 
    description: 'Returns all League of Legends champions with their splash art URLs. Data is read from local JSON file (generated by sync-champions script).' 
  })
  @ApiResponse({ 
    status: 200, 
    description: 'Champion skins retrieved successfully',
    schema: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          championName: { type: 'string', example: 'Aatrox' },
          splashArts: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                skinName: { type: 'string', example: 'Default' },
                skinImageUrl: { type: 'string', example: '/champions/splash/Aatrox_0.webp' },
              },
            },
          },
        },
      },
    },
  })
  async getAllSkins(): Promise<AllSkinsSplashArts[]> {
    this.logger.log('Fetching all champion skins...')
    return this.championsService.getAllChampionSkins()
  }
}

