import { Injectable, Logger, NotFoundException } from '@nestjs/common'
import { readFile } from 'fs/promises'
import { join } from 'path'
import type { AllSkinsSplashArts } from '@loltimeflash/shared'

interface ChampionsData {
  version: string
  lastUpdated: string
  champions: AllSkinsSplashArts[]
}

@Injectable()
export class ChampionsService {
  private readonly logger = new Logger(ChampionsService.name)
  private readonly DATA_FILE_PATH = join(
    process.cwd(),
    '..',
    'web',
    'public',
    'champions',
    'data.json'
  )

  /**
   * Get all champions with their splash arts from local static data
   * @returns Array of champions with their skins
   */
  async getAllChampionSkins(): Promise<AllSkinsSplashArts[]> {
    try {
      // Read from static file generated by sync-champions script
      const fileContent = await readFile(this.DATA_FILE_PATH, 'utf-8')
      const data: ChampionsData = JSON.parse(fileContent)

      this.logger.log(
        `Loaded ${data.champions.length} champions (version: ${data.version}, last updated: ${data.lastUpdated})`
      )

      return data.champions
    } catch (error) {
      this.logger.error('Error reading champions data:', error)

      // If file doesn't exist, provide helpful error message
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
        throw new NotFoundException(
          'Champions data not found. Please run "pnpm sync:champions" first to download champion data.'
        )
      }

      throw new Error('Failed to load champions data')
    }
  }
}

